"""Plan General Contable (PGC) - Cuentas principales para nueva empresa."""

PGC_CUENTAS = [
    # Grupo 1 - Financiero
    ("100", "Capital social"),
    ("102", "Aportaciones sociales"),
    ("103", "Reservas legales"),
    ("104", "Reservas voluntarias"),
    ("106", "Resultados negativos de ejercicios anteriores"),
    ("110", "Suscripciones emitidas"),
    ("112", "Capital emitido pendiente de inscripción"),
    ("118", "Ajustes por cambios de alcance"),
    ("119", "Diferencias de conversión"),
    ("120", "Primas de emisión de acciones"),
    ("121", "Beneficios o pérdidas pendientes de aplicar"),
    ("129", "Resultados de ejercicios anteriores"),
    ("130", "Subvenciones, donaciones y ajustes por cambios de alcance"),
    ("132", "Subvenciones a la explotación"),
    ("133", "Otras subvenciones, donaciones y ajustes"),
    ("134", "Ajustes por valoración en activos no corrientes y grupados enajenados"),
    ("150", "Obligaciones convertible"),
    ("151", "Obligaciones ordinarías"),
    ("153", "Obligaciones subordinadas"),
    ("154", "Deudas con entidades de crédito a lt > 1 año"),
    ("155", "Pagarés a lt > 1 año"),
    ("156", "Préstamos recibidos a lt > 1 año"),
    ("157", "Deudas con entidades de crédito a lt > 1 año - PARTICULARES"),
    ("159", "Anticipos recibidos de clientes - lt > 1 año"),
    ("160", "Empréstitos"),
    ("162", "Otras deudas a lt > 1 año"),
    ("164", "Derechos de reembolso sobre participaciones propias"),
    ("166", "Titanes y obligaciones subordinadas"),
    ("168", "Otras deudas a lt > 1 año - PARTICULAR"),
    ("170", "Proveedores de inmovilizado"),
    ("171", "Acreedores por presupuestos de inmovilizado"),
    ("172", "Proveedores de existencias"),
    ("173", "Acreedores por presupuestos de existencias"),
    ("174", "Proveedores de explotación a lt > 1 año"),
    ("175", "Proveedores de explotación a lt > 1 año - PARTICULAR"),
    ("176", "Retenciones y tributos a cuenta de terceros a lt > 1 año"),
    ("177", "Anticipos de clientes a lt > 1 año"),
    ("178", "Acreedores varios a lt > 1 año"),
    ("180", "Acciones o participaciones emitidas"),
    ("181", "Aportaciones no dinerarias"),
    ("182", "Capital emitido"),
    ("184", "Numerario en caja mayor"),
    ("185", "Depósitos en entidades de crédito a lt > 1 año"),
    ("186", "Derechos de crédito a lt > 1 año"),
    ("189", "Otras inversiones financieras a lt > 1 año"),
    ("190", "Inversiones en instrumentos de patrimonio neto a lt > 1 año"),
    ("191", "Inversiones en participaciones en el capital a lt > 1 año"),
    ("192", "Inversiones en participaciones en el capital a lt > 1 año - GRUPO"),
    ("193", "Inversiones en participaciones en el capital a lt > 1 año - ASOCIADAS"),
    ("194", "Inversiones en instrumentos de patrimonio neto a lt > 1 año - GRUPO"),
    ("195", "Inversiones en instrumentos de patrimonio neto a lt > 1 año - ASOCIADAS"),
    ("196", "Otras inversiones financieras a lt > 1 año"),
    ("198", "Fondos propios a dt > 1 año"),
    ("199", "Diferencias de conversión a lt > 1 año"),

    # Grupo 2 - Existencias
    ("200", "Compras de existencias"),
    ("201", "Compras de mercaderías"),
    ("202", "Compras de materias primas"),
    ("203", "Compras de otros aprovisionamientos"),
    ("204", "Devoluciones de compras sobre mercaderías"),
    ("205", "Devoluciones de compras sobre materias primas"),
    ("206", "Devoluciones de compras sobre otros aprovisionamientos"),
    ("209", "Descuentos por pronto pago en compras de existencias"),
    ("210", "Gastos accesorios de compras de existencias"),
    ("211", "Descuentos por pronto pago en gastos accesorios"),
    ("212", "Trabajos realizados por otras empresas"),
    ("213", "Otros gastos accesorios de compras"),
    ("216", "Descuentos por pronto pago en otros gastos accesorios"),
    ("217", "Recargo de IVA en compras"),
    ("218", "Cuotas de IVA en compras"),
    ("219", "Hacienda pública, repercutida (acreedora)"),
    ("220", "Mercaderías"),
    ("221", "Materias primas"),
    ("222", "Otros aprovisionamientos"),
    ("223", "Reparaciones y conservación"),
    ("224", "Materiales auxiliares, suministros y otros"),
    ("225", "Embalajes"),
    ("226", "Materials de repuesto"),
    ("227", "Herramientas y utillaje"),
    ("228", "Cuadro de mandos y equipo de protección"),
    ("229", "Otras existencias"),
    ("230", "Productos en curso"),
    ("231", "Semielfaborados"),
    ("232", "Productes acabats"),
    ("233", "Productes rebutjats"),
    ("234", "Envases y embalajes prestados"),

    # Grupo 3 - Bienes de Equipo
    ("300", "Inversiones materiales corrientes"),
    ("301", "Terrenos y bienes naturales"),
    ("302", "Edificios e instalaciones"),
    ("303", "Maquinaria, instalaciones y utillaje"),
    ("304", "Instrumentos y herramientas"),
    ("305", "Equipos para procesos de información"),
    ("306", "Elementos de transporte"),
    ("307", "Mobiliario y enseres"),
    ("308", "Otras inversiones materiales"),
    ("309", "Anticipos de inmovilizado material"),
    ("310", "Inmovilizado material en arrendamiento financiero"),
    ("311", "Terrenos y bienes naturales"),
    ("312", "Edificios e instalaciones"),
    ("313", "Maquinaria, instalaciones y utillaje"),
    ("314", "Instrumentos y herramientas"),
    ("315", "Equipos para procesos de información"),
    ("316", "Elementos de transporte"),
    ("317", "Mobiliario y enseres"),
    ("318", "Otras inversiones materiales"),
    ("319", "Anticipos de inmovilizado material en arrendamiento financiero"),
    ("320", "Inversiones inmobiliarias"),
    ("321", "Terrenos"),
    ("322", "Edificios"),
    ("323", "Otras inversiones inmobiliarias"),
    ("324", "Inversiones inmobiliarias en arrendamiento financiero"),
    ("325", "Terrenos en arrendamiento financiero"),
    ("326", "Edificios en arrendamiento financiero"),
    ("327", "Otras inversiones inmobiliarias en arrendamiento financiero"),
    ("328", "Anticipos de inversiones inmobiliarias"),
    ("329", "Provisión para reparación de inmovilizado material"),
    ("330", "Inmovilizado intangible"),
    ("331", "Fondo de comercio"),
    ("332", "Gastos de investigación y desarrollo"),
    ("333", "Concesiones administrativas"),
    ("334", "Propiedad industrial"),
    ("335", "Fórmulas, métodos y otros derechos similares"),
    ("336", "Recursos minerales"),
    ("337", "Derechos de traspaso"),
    ("338", "Aplicaciones informáticas"),
    ("339", "Anticipos de inmovilizado intangible"),
    ("340", "Inmovilizado intangible en arrendamiento financiero"),
    ("341", "Concesiones administrativas en arrendamiento financiero"),
    ("342", "Propiedad industrial en arrendamiento financiero"),
    ("343", "Fórmulas, métodos y otros derechos similares en arrendamiento financiero"),
    ("344", "Recursos minerales en arrendamiento financiero"),
    ("345", "Derechos de traspaso en arrendamiento financiero"),
    ("346", "Aplicaciones informáticas en arrendamiento financiero"),
    ("350", "Inversiones financieras a corto plazo"),
    ("351", "Acciones o participaciones emitidas"),
    ("352", "Otras inversiones en instrumentos de patrimonio neto"),
    ("353", "Derechos de crédito representativos de participaciones en el capital"),
    ("354", "Préstamos cedidos"),
    ("355", "Valores representativos de deuda"),
    ("356", "Otras inversiones financieras"),
    ("357", "Depósitos en entidades de crédito a cp"),
    ("358", "Otros débitos a cp"),
    ("359", "Anticipos a caja y bancos"),
    ("360", "Inversiones financieras a corto plazo - GRUPO"),
    ("361", "Acciones o participaciones emitidas - GRUPO"),
    ("362", "Otras inversiones en instrumentos de patrimonio neto - GRUPO"),
    ("363", "Derechos de crédito representativos de participaciones en el capital - GRUPO"),
    ("364", "Préstamos cedidos - GRUPO"),
    ("365", "Valores representativos de deuda - GRUPO"),
    ("366", "Otras inversiones financieras - GRUPO"),
    ("367", "Depósitos en entidades de crédito a cp - GRUPO"),
    ("368", "Otros débitos a cp - GRUPO"),
    ("369", "Anticipos a caja y bancos - GRUPO"),
    ("370", "Inversiones financieras a corto plazo - ASOCIADAS"),
    ("371", "Acciones o participaciones emitidas - ASOCIADAS"),
    ("372", "Otras inversiones en instrumentos de patrimonio neto - ASOCIADAS"),
    ("373", "Derechos de crédito representativos de participaciones en el capital - ASOCIADAS"),
    ("374", "Préstamos cedidos - ASOCIADAS"),
    ("375", "Valores representativos de deuda - ASOCIADAS"),
    ("376", "Otras inversiones financieras - ASOCIADAS"),
    ("377", "Depósitos en entidades de crédito a cp - ASOCIADAS"),
    ("378", "Otros débitos a cp - ASOCIADAS"),
    ("379", "Anticipos a caja y bancos - ASOCIADAS"),
    ("390", "Amortización acumulada del inmovilizado material"),
    ("391", "Amortización acumulada del inmovilizado material - Terrenos y bienes naturales"),
    ("392", "Amortización acumulada del inmovilizado material - Edificios e instalaciones"),
    ("393", "Amortización acumulada del inmovilizado material - Maquinaria, instalaciones y utillaje"),
    ("394", "Amortización acumulada del inmovilizado material - Instrumentos y herramientas"),
    ("395", "Amortización acumulada del inmovilizado material - Equipos para procesos de información"),
    ("396", "Amortización acumulada del inmovilizado material - Elementos de transporte"),
    ("397", "Amortización acumulada del inmovilizado material - Mobiliario y enseres"),
    ("398", "Amortización acumulada del inmovilizado material - Otras inversiones materiales"),
    ("399", "Amortización acumulada del inmovilizado material en arrendamiento financiero"),
    ("400", "Acreedores por compras de existencias (mercaderías, materias primas y otros aprovisionamientos)"),
    ("401", "Proveedores"),
    ("402", "Proveedores de efectos comerciales"),
    ("403", "Acreedores por compras de existencias (mercaderías, materias primas y otros aprovisionamientos) - GRUPO"),
    ("404", "Proveedores - GRUPO"),
    ("405", "Proveedores de efectos comerciales - GRUPO"),
    ("406", "Acreedores por compras de existencias (mercaderías, materias primas y otros aprovisionamientos) - ASOCIADAS"),
    ("407", "Proveedores - ASOCIADAS"),
    ("408", "Proveedores de efectos comerciales - ASOCIADAS"),
    ("409", "Descuentos por pronto pago en compras de existencias"),
    ("410", "Acreedores por trabajos realizados por otras empresas"),
    ("411", "Acreedores por otros bienes y servicios"),
    ("412", "Acreedores por presupuestos"),
    ("413", "Acreedores por compras de otros aprovisionamientos"),
    ("414", "Anticipos de clientes"),
    ("416", "Acreedores por prestaciones de servicios"),
    ("417", "Acreedores por tributos"),
    ("418", "Acreedores por retenciones y tributos a cuenta"),
    ("419", "Acreedores varios"),
    ("420", "Organismos de la Seguridad Social"),
    ("421", "Acreedores por salarios"),
    ("422", "Acreedores por pagos en especie"),
    ("423", "Acreedores por dividendos a favor de terceros"),
    ("424", "Acreedores por intereses"),
    ("425", "Otros acreedores"),
    ("426", "Administraciones públicas - IVA soportado"),
    ("427", "Hacienda Pública - IVA repercutido"),
    ("428", "Otros tributos - IVA"),
    ("429", "Hacienda Pública - otros tributos"),
    ("430", "Hacienda Pública - IRPF"),
    ("431", "Hacienda Pública - retenciones y pagos a cuenta"),
    ("432", "Hacienda Pública - impuesto sobre sociedades"),
    ("433", "Hacienda Pública - otros tributos corrientes"),
    ("434", "Organismos de la Seguridad Social - cuotas obrero-patronales"),
    ("435", "Hacienda Pública - subvenciones a devolver"),
    ("436", "Organismos de la Seguridad Social - cuotas trabajadores"),
    ("437", "Hacienda Pública - anticipos de impuesto sobre sociedades"),
    ("438", "Hacienda Pública - dividendos a favor"),
    ("439", "Hacienda Pública - intereses a favor"),
    ("440", "Clientes"),
    ("441", "Clientes - efectos comerciales a cobrar"),
    ("442", "Clientes - retenciones y descuentos aplicados"),
    ("443", "Clientes - operaciones de venta a plazo"),
    ("444", "Clientes - IVA repercutido"),
    ("445", "Clientes - descuento por pronto pago"),
    ("446", "Clientes - devoluciones de ventas"),
    ("447", "Clientes - garantías y avances"),
    ("449", "Deudores varios"),
    ("460", "Empresas del grupo: deudores por préstamos"),
    ("461", "Empresas del grupo: deudores por operaciones corrientes"),
    ("462", "Empresas del grupo: deudores por dividendos"),
    ("463", "Empresas del grupo: deudores por enajenación de inmovilizado"),
    ("464", "Empresas del grupo: deudores por otras inversiones"),
    ("465", "Empresas del grupo: otros deudores"),
    ("466", "Asociadas: deudores por préstamos"),
    ("467", "Asociadas: deudores por operaciones corrientes"),
    ("468", "Asociadas: deudores por dividendos"),
    ("469", "Asociadas: otros deudores"),
    ("470", "Particular: deudores por préstamos"),
    ("471", "Particular: deudores por operaciones corrientes"),
    ("472", "Particular: deudores por dividendos"),
    ("473", "Particular: deudores por enajenación de inmovilizado"),
    ("474", "Particular: deudores por otras inversiones"),
    ("475", "Particular: otros deudores"),
    ("476", "Deudores por subvenciones"),
    ("477", "Deudores por operaciones en común"),
    ("480", "Activos no corrientes y grupados enajenados"),
    ("481", "Pasivos vinculados a activos no corrientes y grupados enajenados"),
    ("485", "Socios por desembolsos no exigidos - Capital social"),
    ("486", "Socios por desembolsos no exigidos - Prima de emisión"),
    ("487", "Socios por desembolsos no exigidos - Reservas"),
    ("488", "Socios por desembolsos no exigidos - Otras aportaciones"),
    ("489", "Socios por desembolsos no exigidos - Otros conceptos"),
    ("490", "Provisiones por depreciación de existencias"),
    ("491", "Provisiones por depreciación de existencias - Mercaderías"),
    ("492", "Provisiones por depreciación de existencias - Materias primas"),
    ("493", "Provisiones por depreciación de existencias - Otros aprovisionamientos"),
    ("494", "Provisiones por depreciación de existencias - Productos en curso"),
    ("495", "Provisiones por depreciación de existencias - Productos semielaborados"),
    ("496", "Provisiones por depreciación de existencias - Productos acabados"),
    ("497", "Provisiones por depreciación de existencias - Productos rechazados"),
    ("498", "Provisiones por depreciación de existencias - Envases y embalajes"),
    ("499", "Provisiones por depreciación de existencias - Otras existencias"),
    ("500", "Numerario y caja"),
    ("501", "Caja principal"),
    ("502", "Caja auxiliar o caja chica"),
    ("503", "Talones pendientes de presentar"),
    ("504", "Cheques bancarios en cartera"),
    ("505", "Pagos por transferencia"),
    ("506", "Libretas de ahorro"),
    ("509", "Otros valores convertibles en efectivo"),
    ("510", "Depósitos en entidades de crédito a cp"),
    ("511", "Letras del Tesoro en cartera"),
    ("512", "Otras inversiones financieras a corto plazo"),
    ("513", "Depósitos en entidades de crédito a cp - GRUPO"),
    ("514", "Depósitos en entidades de crédito a cp - ASOCIADAS"),
    ("515", "Letras del Tesoro en cartera - GRUPO"),
    ("516", "Otras inversiones financieras a corto plazo - GRUPO"),
    ("517", "Letras del Tesoro en cartera - ASOCIADAS"),
    ("518", "Otras inversiones financieras a corto plazo - ASOCIADAS"),
    ("519", "Clases de fondos - Moneda local"),
    ("520", "Derechos de crédito a cp"),
    ("521", "Clientes - deudas enarteriores al ejercicio"),
    ("522", "Efectos comerciales a cobrar"),
    ("523", "Efectos de establecimientos de hostelería"),
    ("524", "Anticipos de caja fija"),
    ("525", "Títulos-valores a cobrar"),
    ("526", "Valores y depósitos en garantía"),
    ("527", "Derechos de crédito a cp - GRUPO"),
    ("528", "Clientes - deudas anteriores al ejercicio - GRUPO"),
    ("529", "Efectos comerciales a cobrar - GRUPO"),
    ("530", "Otros débitos a cp"),
    ("531", "Deudores varios"),
    ("532", "Deudores por dividendos"),
    ("533", "Deudores por intereses"),
    ("534", "Deudores por subvenciones"),
    ("535", "Deudores por operaciones en común"),
    ("536", "Deudores varios - GRUPO"),
    ("537", "Deudores por dividendos - GRUPO"),
    ("538", "Deudores por intereses - GRUPO"),
    ("539", "Anticipos de dividendos"),
    ("540", "Depósitos recibidos de garantía"),
    ("541", "Depósitos y fianzas prestados"),
    ("542", "Depósitos y fianzas reembolsables"),
    ("543", "Títulos-valores depositados en garantía"),
    ("544", "Otros depósitos de garantía"),
    ("545", "Valores depositados - PARTICULAR"),
    ("546", "Depósitos y fianzas prestados - PARTICULAR"),
    ("547", "Depósitos recibidos de garantía - PARTICULAR"),
    ("548", "Otros depósitos de garantía - PARTICULAR"),
    ("549", "Depósitos en garantía a cp"),
    ("550", "Hacienda Pública - IVA soportado"),
    ("551", "Hacienda Pública - IVA repercutido"),
    ("552", "Hacienda Pública - retenciones y tributos a cuenta"),
    ("553", "Hacienda Pública - IRPF"),
    ("554", "Hacienda Pública - impuesto sobre sociedades"),
    ("555", "Hacienda Pública - otros tributos"),
    ("556", "Organismos de la Seguridad Social"),
    ("557", "Hacienda Pública - subvenciones a devolver"),
    ("558", "Hacienda Pública - dividendos a favor"),
    ("559", "Hacienda Pública - intereses a favor"),
    ("560", "Otros créditos a cp"),
    ("561", "Anticipos de dietas y gastos"),
    ("562", "Personal - anticipos"),
    ("563", "Acreedores por anticipos de dividendos"),
    ("564", "Acreedores por anticipos de intereses"),
    ("565", "Anticipos a proveedores"),
    ("566", "Anticipos de caja fija - otros"),
    ("567", "Depósitos recibidos de garantía - otros"),
    ("568", "Otros débitos a cp - PARTICULAR"),
    ("569", "Anticipos a largo plazo - cp"),
    ("570", "Instrumentos financieros derivados - cotizados en mercados organizados"),
    ("571", "Instrumentos financieros derivados - divisas"),
    ("572", "Instrumentos financieros derivados - tipos de interés"),
    ("573", "Instrumentos financieros derivados - otros"),
    ("574", "Instrumentos financieros derivados - divisa - GRUPO"),
    ("575", "Instrumentos financieros derivados - divisa - ASOCIADAS"),
    ("576", "Instrumentos financieros derivados - tipo interés - GRUPO"),
    ("577", "Instrumentos financieros derivados - tipo interés - ASOCIADAS"),
    ("578", "Instrumentos financieros derivados - otros - GRUPO"),
    ("579", "Instrumentos financieros derivados - otros - ASOCIADAS"),
    ("580", "Deterioro del valor de la cartera de valores a cp"),
    ("581", "Deterioro del valor de la cartera de valores a cp - Coste amortizado"),
    ("582", "Deterioro del valor de la cartera de valores a cp - Disponible para la venta"),
    ("583", "Deterioro del valor de la cartera de valores a cp - Otros"),
    ("584", "Deterioro del valor de la cartera de valores a cp - Coste amortizado - GRUPO"),
    ("585", "Deterioro del valor de la cartera de valores a cp - Coste amortizado - ASOCIADAS"),
    ("586", "Deterioro del valor de la cartera de valores a cp - Disponible para la venta - GRUPO"),
    ("587", "Deterioro del valor de la cartera de valores a cp - Disponible para la venta - ASOCIADAS"),
    ("588", "Deterioro del valor de la cartera de valores a cp - Otros - GRUPO"),
    ("589", "Deterioro del valor de la cartera de valores a cp - Otros - ASOCIADAS"),
    ("590", "Amortización del inmovilizado financiero a cp"),
    ("591", "Amortización de inversiones financieras en instrumentos de patrimonio neto"),
    ("592", "Amortización de otros valores emitidos"),
    ("593", "Amortización de otros activos financieros"),
    ("594", "Amortización de inversiones en el capital o patrimonio neto - GRUPO"),
    ("595", "Amortización de otros valores emitidos - GRUPO"),
    ("596", "Amortización de otros activos financieros - GRUPO"),
    ("597", "Amortización de inversiones en el capital o patrimonio neto - ASOCIADAS"),
    ("598", "Amortización de otros valores emitidos - ASOCIADAS"),
    ("599", "Amortización de otros activos financieros - ASOCIADAS"),
    ("600", "Gastos de personal: salarios y jornales"),
    ("601", "Sueldos y salarios"),
    ("602", "Indemnizaciones"),
    ("603", "Seguridad social a cargo de la empresa"),
    ("604", "Otros gastos de personal"),
    ("605", "Aportaciones a planes de pensiones"),
    ("606", "Gastos de personal - GRUPO"),
    ("607", "Sueldos y salarios - GRUPO"),
    ("608", "Indemnizaciones - GRUPO"),
    ("609", "Seguridad social a cargo de la empresa - GRUPO"),
    ("610", "Otros gastos de personal - GRUPO"),
    ("620", "Gastos corrientes en bienes y servicios"),
    ("621", "Trabajos realizados por otras empresas"),
    ("622", "Transportes"),
    ("623", "Reparaciones y conservación"),
    ("624", "Servicios de profesionales independientes"),
    ("625", "Primas de seguros"),
    ("626", "Servicios bancarios y similares"),
    ("627", "Otros servicios exteriores"),
    ("628", "Trabajos realizados por empresas del grupo"),
    ("629", "Trabajos realizados por asociadas"),
    ("630", "Tributos"),
    ("631", "Impuesto sobre actividades económicas"),
    ("632", "Otros tributos corrientes"),
    ("633", "Impuestos sobre beneficios - pago fraccionado"),
    ("634", "Otros tributos - IVA"),
    ("635", "Otros tributos - IVA deducible"),
    ("636", "Otros tributos - retenciones"),
    ("637", "Impuesto sobre beneficios"),
    ("638", "Recargo de equivalencia"),
    ("639", "Otros tributos corrientes - GRUPO"),
    ("640", "Seguridad social a cargo de la empresa"),
    ("641", "Otros gastos de personal corrientes"),
    ("642", "Gastos de personal - otros"),
    ("643", "Gastos de personal - dietas y viajes"),
    ("644", "Gastos de personal - formación"),
    ("645", "Gastos de personal - otros - GRUPO"),
    ("646", "Gastos de personal corrientes - GRUPO"),
    ("650", "Otros gastos de gestión corrientes"),
    ("651", "Pérdidas de créditos comerciales"),
    ("652", "Resultados de operaciones en común - pérdida"),
    ("653", "Pérdidas por diferencia de cambio"),
    ("654", "Pérdidas en valores mobiliarios de inversiones a cp"),
    ("655", "Gastos financieros de deudas con entidades del grupo"),
    ("656", "Gastos financieros de deudas con asociadas"),
    ("657", "Gastos financieros de deudas con particulares"),
    ("658", "Otros gastos financieros"),
    ("659", "Deterioro del valor de participaciones en el capital y otros valores representativos del neto"),
    ("660", "Gastos financieros"),
    ("661", "Intereses de deudas a cp con entidades de crédito"),
    ("662", "Intereses de deudas a lt con entidades de crédito"),
    ("663", "Intereses de letras del Tesoro"),
    ("664", "Intereses de deudas con empresas del grupo"),
    ("665", "Intereses de deudas con asociadas"),
    ("666", "Intereses de deudas con particulares"),
    ("667", "Otras pérdidas financieras"),
    ("668", "Pérdidas en participaciones y otros valores representativos del neto"),
    ("669", "Pérdidas por depreciación de valores mobiliarios"),
    ("670", "Gastos excepcionales"),
    ("671", "Pérdidas extraordinarias"),
    ("672", "Gastos excepcionales - otros"),
    ("673", "Pérdidas por operaciones con capital propio"),
    ("674", "Subvenciones a la explotación concedidas y no reintegrables cuya devolución no se prevea"),
    ("675", "Pérdidas por operaciones no habituales"),
    ("676", "Pérdidas por deterioro del valor de participaciones y otros valores representativos del neto en el largo plazo"),
    ("677", "Pérdidas por deterioro del valor de participaciones y otros valores representativos del neto en el corto plazo"),
    ("678", "Pérdidas por deterioro del valor de otros activos fijos"),
    ("679", "Ajustes en pérdidas por valoración de activos no corrientes y grupados enajenados"),
    ("680", "Dotación a la amortización del inmovilizado"),
    ("681", "Dotación a la amortización del inmovilizado intangible"),
    ("682", "Dotación a la amortización del inmovilizado material"),
    ("683", "Dotación a la amortización de inversiones inmobiliarias"),
    ("684", "Dotación a la amortización del inmovilizado en arrendamiento financiero"),
    ("685", "Dotación a la amortización del inmovilizado - GRUPO"),
    ("686", "Dotación a la amortización del inmovilizado - ASOCIADAS"),
    ("690", "Dotación a las provisiones de la empresa"),
    ("691", "Dotación a las provisiones para despido de personal"),
    ("692", "Dotación a las provisiones por retribuciones a largo plazo del personal"),
    ("693", "Dotación a las provisiones por operaciones de mantenimiento y reparación"),
    ("694", "Dotación a las provisiones por contratos onerosos"),
    ("695", "Dotación a las provisiones por garantías a clientes"),
    ("696", "Dotación a las provisiones por pérdidas en operaciones de cobertura"),
    ("697", "Dotación a las provisiones por otros conceptos"),
    ("698", "Dotación a las provisiones para la gestión de la depreciación de existencias"),
    ("699", "Dotación a las provisiones para la gestión de la depreciación de existencias - GRUPO"),
    ("700", "Ingresos de las actividades ordinarias"),
    ("701", "Ventas de mercaderías"),
    ("702", "Ventas de productos acabados"),
    ("703", "Ventas de productos semielaborados"),
    ("704", "Ventas de productos en curso"),
    ("705", "Ventas de servicios"),
    ("706", "Descuentos sobre ventas por pronto pago"),
    ("707", "Devoluciones de ventas sobre mercaderías"),
    ("708", "Descuentos por pronto pago en ventas de existencias"),
    ("709", "Requisitos e igualas"),
    ("710", "Trabajos realizados por otras empresas"),
    ("711", "Reparaciones y conservación"),
    ("712", "Primas de seguros"),
    ("713", "Transportes"),
    ("714", "Comisiones"),
    ("715", "Otros servicios exteriores"),
    ("716", "Otros servicios exteriores - otros"),
    ("717", "Trabajos realizados por empresas del grupo"),
    ("718", "Trabajos realizados por asociadas"),
    ("719", "Comisiones y corretajes por ventas"),
    ("720", "Subvenciones a la explotación"),
    ("721", "Subvenciones a la explotación - particulares"),
    ("722", "Subvenciones a la explotación - organismos públicos"),
    ("723", "Subvenciones a la explotación - empresas del grupo"),
    ("724", "Subvenciones a la explotación - asociadas"),
    ("725", "Subvenciones a la explotación - otras"),
    ("726", "Ingresos por arrendamientos"),
    ("727", "Ingresos por arrendamientos de inmovilizado material"),
    ("728", "Ingresos por arrendamientos de inmovilizado intangible"),
    ("729", "Ingresos por arrendamientos de inversiones inmobiliarias"),
    ("730", "Ingresos por arrendamientos - GRUPO"),
    ("731", "Ingresos por arrendamientos de inmovilizado material - GRUPO"),
    ("732", "Ingresos por arrendamientos de inmovilizado intangible - GRUPO"),
    ("733", "Ingresos por arrendamientos de inversiones inmobiliarias - GRUPO"),
    ("734", "Ingresos por arrendamientos - ASOCIADAS"),
    ("735", "Ingresos por arrendamientos de inmovilizado material - ASOCIADAS"),
    ("736", "Ingresos por arrendamientos de inmovilizado intangible - ASOCIADAS"),
    ("737", "Ingresos por arrendamientos de inversiones inmobiliarias - ASOCIADAS"),
    ("738", "Ingresos por arrendamientos - PARTICULARES"),
    ("739", "Ingresos por arrendamientos de inmovilizado material - PARTICULARES"),
    ("740", "Resultados de operaciones en común - beneficio"),
    ("741", "Resultados de operaciones en común - beneficio - PARTICULARES"),
    ("742", "Resultados de operaciones en común - beneficio - GRUPO"),
    ("743", "Resultados de operaciones en común - beneficio - ASOCIADAS"),
    ("750", "Otros ingresos de gestión"),
    ("751", "Ingresos por servicios auxiliares"),
    ("752", "Exceso de provisiones"),
    ("753", "Ingresos por operaciones en común"),
    ("754", "Beneficios en operaciones de cobertura"),
    ("755", "Ingresos por dividendos de participaciones en el neto"),
    ("756", "Ingresos por dividendos - GRUPO"),
    ("757", "Ingresos por dividendos - ASOCIADAS"),
    ("758", "Ingresos por dividendos - PARTICULARES"),
    ("759", "Otros ingresos financieros a cp"),
    ("760", "Ingresos financieros"),
    ("761", "Intereses de deudas a cp con entidades de crédito"),
    ("762", "Intereses de deudas a lt con entidades de crédito"),
    ("763", "Intereses de letras del Tesoro"),
    ("764", "Intereses de deudas con empresas del grupo"),
    ("765", "Intereses de deudas con asociadas"),
    ("766", "Intereses de deudas con particulares"),
    ("767", "Otros ingresos financieros"),
    ("768", "Ingresos por participaciones en el capital y otros valores representativos del neto"),
    ("769", "Ingresos por depreciación de valores mobiliarios"),
    ("770", "Ingresos excepcionales"),
    ("771", "Ingresos extraordinarios"),
    ("772", "Ingresos excepcionales - otros"),
    ("773", "Ingresos por operaciones con capital propio"),
    ("774", "Subvenciones a la explotación reintegrables concedidas y no reintegrables cuya devolución se prevea"),
    ("775", "Ingresos por operaciones no habituales"),
    ("776", "Ingresos por deterioro del valor de participaciones y otros valores representativos del neto en el largo plazo"),
    ("777", "Ingresos por deterioro del valor de participaciones y otros valores representativos del neto en el corto plazo"),
    ("778", "Ingresos por deterioro del valor de otros activos fijos"),
    ("779", "Ajustes en ingresos por valoración de activos no corrientes y grupados enajenados"),
    ("780", "Beneficio procedente de subvenciones de capital - inversiones en inmovilizado"),
    ("781", "Beneficio procedente de subvenciones de capital - inversiones en existencias"),
    ("782", "Beneficio procedente de subvenciones de capital - otras inversiones"),
    ("783", "Beneficio procedente de subvenciones de capital - otras"),
    ("784", "Beneficio procedente de subvenciones a la explotación"),
    ("785", "Beneficio procedente de subvenciones de capital - inversiones en inmovilizado - GRUPO"),
    ("786", "Beneficio procedente de subvenciones de capital - inversiones en existencias - GRUPO"),
    ("787", "Beneficio procedente de subvenciones de capital - otras inversiones - GRUPO"),
    ("788", "Beneficio procedente de subvenciones de capital - otras - GRUPO"),
    ("789", "Beneficio procedente de subvenciones a la explotación - GRUPO"),
    ("790", "Beneficio del ejercicio"),
    ("791", "Beneficio del ejercicio - PARTICULARES"),
    ("792", "Beneficio del ejercicio - GRUPO"),
    ("793", "Beneficio del ejercicio - ASOCIADAS"),
    ("794", "Gasto imponible - sociedades"),
    ("795", "Partición del beneficio - dividendos"),
    ("796", "Partición del beneficio - otras formas de distribución"),
    ("797", "Gasto imponible - IRPF"),
    ("798", "Gasto imponible - otros impuestos"),
    ("799", "Beneficio del ejercicio - otras formas de distribución"),
]


def crear_plan_cuentas(db, empresa_id: int):
    """Crea el Plan General Contable para una empresa."""
    from app.models.contabilidad import Cuenta
    cuentas = []
    for codigo, texto in PGC_CUENTAS:
        cuenta = Cuenta(
            empresa_id=empresa_id,
            cuenta=codigo,
            texto=texto,
            debe=0,
            haber=0,
        )
        cuentas.append(cuenta)
    db.add_all(cuentas)
    db.commit()
    return len(cuentas)
